workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: iOS Kairo
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.blockexplosion
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
      node: 22
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Add iOS platform
        script: |
          npx cap add ios
      - name: Generate app icons
        script: |
          npm install -g @capacitor/assets
          mkdir -p resources
          cp src/assets/app-icon.png resources/icon.png
          npx capacitor-assets generate --ios
      - name: Copy audio files to iOS
        script: |
          mkdir -p ios/App/App/sounds
          cp public/assets/sounds/*.mp3 ios/App/App/sounds/
          echo "Audio files copied to iOS project"
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Verify iOS setup
        script: |
          ls -la ios/App/
          test -d ios/App/App.xcodeproj && echo "Project exists" || exit 1
      - name: Set version
        script: |
          cd ios/App
          agvtool new-marketing-version 1.0.0
          agvtool new-version -all $BUILD_NUMBER
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
